name: Deploy to AWS

on:
    push:
        branches:
        - master
        - main
    pull_request:
        branches:
        - master
        - main
        - staging
        - develop
        - feature/*
        - hotfix/*
        - release/*
        - bugfix/*
        - docs/*
        - refactor/*
        - style/*
        - test/*
        - ci/*
        - chore/*
        - revert/*
        - fix/*
        - perf/*`
        - security/*
        - build/*
        - config/*
        - deploy/*
        - dependency/*
        - merge/*
        - version/*
        - sync/*
        - init/*
        - add/*
        - remove/*
        - create/*
        - delete/*
        - upgrade/*
        - downgrade/*
        - revert/*
        - move/*
        - rename/*
        - copy/*
        - resolve/*
        - improve/*
        - make/*
        - start/*
        - stop/*
        - finish/*
        - cancel/*
        - debug/*
        - publish/*
        - draft/*
        - tag/*
        - backport/*
        - squash/*
        - rebase/*
        - fixup/*
        - revert/*
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      issues: write
      checks: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 # Change this to your preferred region

      - name: Deploy to S3
        run: |
          aws s3 cp ./dist/ s3://my-bucket-name/ --recursive

# Secrets are defined in the repository settings

# AWS_ACCESS_KEY_ID
# AWS_SECRET_ACCESS_KEY